### ISSUE TITLE
Add web feed

### ISSUE THREAD

**Issue by sjehuda** [diso/website#3]
I'm listing web sites of interest in the "Help" section with "feeds to start with" in my [userscript](https://openuserjs.org/scripts/sjehuda/Newspaper) feed reader.

Please add a feed so DiSo be featured there too.

**Comment by pfefferle** [comment]
Hey @sjehuda this site is a "historical document" and no longer actively maintained, so I would think that a feed does not provide any real value :)

**Comment by sjehuda** [comment]
The advantage of a feed is that it can be somewhere in the database,
and when it will be updated, then so be it.

I do think that a feed would be of benefit here.
